require_relative 'instance_counter'
require_relative 'validation'
require_relative 'station'
require_relative 'route'
require_relative 'manufacturer'
require_relative 'train'
require_relative 'passenger_train'
require_relative 'cargo_train'
require_relative 'wagon'
require_relative 'passenger_wagon'
require_relative 'cargo_wagon'
require_relative 'lib/seed'
require_relative 'lib/menu/basis_menu'
require_relative 'lib/menu/main_menu'
require_relative 'lib/menu/creating_menu'
require_relative 'lib/menu/manage_route_menu'
require_relative 'lib/menu/manage_train_menu'
require_relative 'lib/menu/manage_wagon_menu'
require_relative 'lib/menu/info_menu'
require_relative 'lib/menu/info_detailed_menu'

MainMenu.new
