require_relative 'lib/instance_counter'
require_relative 'lib/validation'
require_relative 'lib/station'
require_relative 'lib/route'
require_relative 'lib/manufacturer'
require_relative 'lib/train'
require_relative 'lib/passenger_train'
require_relative 'lib/cargo_train'
require_relative 'lib/wagon'
require_relative 'lib/passenger_wagon'
require_relative 'lib/cargo_wagon'
require_relative 'lib/seed'
require_relative 'lib/menu/basis_menu'
require_relative 'lib/menu/main_menu'
require_relative 'lib/menu/creating_menu'
require_relative 'lib/menu/manage_route_menu'
require_relative 'lib/menu/manage_train_menu'
require_relative 'lib/menu/manage_wagon_menu'
require_relative 'lib/menu/info_menu'
require_relative 'lib/menu/info_detailed_menu'

MainMenu.new
